#!/bin/sh

mount -t devtmpfs devtmpfs /dev
mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t tmpfs tmpfs /run

[ -d /mnt/rootmnt ] || mkdir -p /mnt/rootmnt]
mount /dev/sda1 /mnt/rootmnt

cd /mnt/rootmnt
exec switch_root . "/init" "$@"
